### ISSUE TITLE
TPM or fold change for time series dataset without treatment

### ISSUE THREAD

**Issue by mahnaz65** [PrincetonUniversity/DP_GP_cluster#25]
I have a RNA-seq dataset from different developmental time points and I want to make clustering genes. I do not have any treatment or condition accompanied with different time points. what value will be imported into DP-GP? In the some articles, they used standardized fold change derived from comparisons of treatment and control in each time point, but I do not have different condition, so I think I must use TPM to import for clustering. Am I right?

**Comment by IanMcDowell** [comment]
You should obtain log fold change values by comparing each timepoint to timepoint 0. This is the best and most common way to deal with your use case. Then you can standardize the log fold change values at each timepoint. If you use a differential gene expression algorithm, like edgeR or DESeq2, to obtain your log fold change values, this has the added bonus of giving you p-values and adjusted p-values. You could use the adjusted p-values to subset only those genes that significantly vary in expression over the developmental time course. Otherwise, you would be left to cluster many genes that would hover around 0 in log fold change across the time course, which are of little use to cluster and, indeed, greatly frustrate clustering.
